name: Run pytest tests

on: [ push ]

jobs:
  integration-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.13.0
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: '1.8.2'

      - name: Poetry build
        run: poetry build

      - name: Run tests for old API
        run: poetry run pytest tests

      - name: Run tests for new API and parser
        run: poetry run pytest test

  gate-2:
    name: Gate 2 - Allow Merge
    runs-on: ubuntu-latest
    needs: [ integration-tests ]
    steps:
      - name: Branch Protection
        run: true
