name: Run pytest tests

on: [ push ]

jobs:
  integration_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.0
      - name: Poetry install
        run: poetry install

      - name: Poetry build
        run: poetry build

      - name: Run tests for old API
        run: poetry run pytest tests

      - name: Run tests for new API and parser
        run: poetry run pytest test
