name: CI

on: [ push ]

jobs:
  ci-job:
    name: Integration tests (Python-${{ matrix.python-version }})
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.13.0
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: '1.8.2'

      - name: Poetry build
        run: poetry build

      - name: Run tests for old API
        run: poetry run pytest tests

      - name: Run tests for new API and parser
        run: poetry run pytest test

  gate-1:
    name: Gate 1 - Regular CI
    needs: [ ci-job ]
    runs-on: ubuntu-latest
    steps:
      - name: Branch Protection
        run: true
